// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright 2026 Sam Blenny
"use strict";

const STATUS = document.querySelector('#status');
const CONNECT = document.querySelector('#connect');
const VIDEO = document.querySelector('#video');
const SERVER_URL = document.querySelector('#serverUrl');

let WEB_RTC = null;

// Update status line span
function setStatus(s) {
    STATUS.textContent = s;
}

// Disconnect and stop updating the video
async function disconnect(status) {
    if (WEB_RTC) {
        // TODO: proper WebRTC cleanup
        WEB_RTC = null;
    }
    CONNECT.classList.remove('on');
    CONNECT.textContent = 'Connect';
    setStatus(status ? status : 'disconnected');
}

// Attempt to establish WebRTC connection to gstreamer server
function connect() {
    const url = SERVER_URL.value.trim();

    if (!url) {
        setStatus('error: no server URL');
        return;
    }

    setStatus('connecting...');

    // Read server URL from input field
    console.log('[WebRTC] Server URL:', url);

    // Step 1: Create RTCPeerConnection for media exchange
    console.log('[WebRTC] Creating RTCPeerConnection');

    // Step 2: Generate SDP offer describing what browser can send/receive.
    // SDP (Session Description Protocol) is a standard format for describing
    // media capabilities and network parameters.
    console.log('[WebRTC] Generating SDP offer');

    // Step 3: Send offer to SBC via HTTP POST to /offer endpoint.
    // Server will respond with SDP answer describing its capabilities.
    console.log('[WebRTC] POST offer to /offer endpoint');

    // Step 4: Receive SDP answer from server
    console.log('[WebRTC] Received SDP answer from server');

    // Step 5: Set remote description with answer. This tells RTCPeerConnection
    // what the remote peer (server) is sending.
    console.log('[WebRTC] Setting remote description with answer');

    // Step 6: Set up ICE candidate handler. ICE (Interactive Connectivity
    // Establishment) discovers network paths between peers by exchanging
    // candidates (possible addresses they can receive on). Both sides generate
    // candidates and test which ones have working connectivity.
    console.log('[WebRTC] Setting up ICE candidate exchange');

    // Step 7: Listen for local ICE candidates generated by browser.
    // Each candidate will be sent to server via POST /ice-candidate.
    console.log('[WebRTC] Listening for local ICE candidates');

    // Step 8: Set up handler for remote video track from server.
    // When server sends VP8 video, attach it to the video element.
    console.log('[WebRTC] Setting up remote track handler');
    console.log('[WebRTC] Attaching remote video to #video element');

    // On successful connection:
    // CONNECT.classList.add('on');
    // CONNECT.textContent = 'Disconnect';
    // setStatus('connected');
}

// Add on/off event handlers to the button
CONNECT.addEventListener('click', function() {
    if(CONNECT.classList.contains('on')) {
        disconnect();
    } else {
        connect();
    }
});

setStatus("ready");
